"""Fix company model

Revision ID: f6d20edfdaf4
Revises: f6180c411b19
Create Date: 2025-09-12 08:58:20.792259

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f6d20edfdaf4'
down_revision: Union[str, Sequence[str], None] = 'f6180c411b19'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'release', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'release', type_='unique')
    # ### end Alembic commands ###
